## Speed comparision

In [1]:
a = [i for i in range(10000000)]
b = [i for i in range(10000000, 20000000)]

c=[]

import time

start=time.time()
for i in range(len(a)):
    c.append(a[i] + b[i])
print(time.time()-start)

0.7233612537384033


In [2]:
import numpy as np # use ctype array not referencial array , ctype a static array 
a=np.arange(10000000)
b=np.arange(10000000, 20000000)
start=time.time()
c=a+b
print(time.time()-start)

0.06303811073303223


In [3]:
0.791/0.059

13.40677966101695

In [4]:
#memory

a=[i for i in range(10000000)]
import sys 
sys.getsizeof(a)

89095160

In [5]:
a=np.arange(10000000,dtype=np.int8)
sys.getsizeof(a)


10000112

In [6]:
#convenience


## Adavnced Indexing

In [7]:
a=np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [8]:
a[1:3,1:3]

array([[4, 5],
       [7, 8]])

In [9]:
a=np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [10]:
a[1,2] # indexing

np.int64(5)

In [11]:
a[1:3,1:3] #slicing

array([[4, 5],
       [7, 8]])

In [13]:
#Fancy Indexing
# a[::2]

a[[0,2,3]]


array([[ 0,  1,  2],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [14]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [15]:
a=np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [16]:
a[[0,2,3,5]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [17]:
a[:,[0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [18]:
import numpy as np

a = np.arange(24).reshape(6, 4)
print(a)



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [19]:
a = a[:, [0, 2, 3]]
print(a)

[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]
 [12 14 15]
 [16 18 19]
 [20 22 23]]


In [20]:
# Boolean Indexing
import numpy as np
a=np.random.randint(1,100,24).reshape(6,4)
a

array([[29, 36, 26, 58],
       [92, 69, 20, 17],
       [66, 91, 45, 47],
       [69, 58, 30, 36],
       [ 5, 54, 72, 20],
       [30, 27, 39, 56]], dtype=int32)

In [21]:
# find all values greater than 50
a>50

array([[False, False, False,  True],
       [ True,  True, False, False],
       [ True,  True, False, False],
       [ True,  True, False, False],
       [False,  True,  True, False],
       [False, False, False,  True]])

In [22]:
a[a>50]

array([58, 92, 69, 66, 91, 69, 58, 54, 72, 56], dtype=int32)

In [23]:
#find out the even numbers

a%2==0


array([[False,  True,  True,  True],
       [ True, False,  True, False],
       [ True, False, False, False],
       [False,  True,  True,  True],
       [False,  True,  True,  True],
       [ True, False, False,  True]])

In [24]:
a[a%2==0]

array([36, 26, 58, 92, 20, 66, 58, 30, 36, 54, 72, 20, 30, 56],
      dtype=int32)

In [25]:
 # find out the even numbers greater than 50


a[(a%2==0) & (a>50)]# & for bitwise and
 

array([58, 92, 66, 58, 54, 72, 56], dtype=int32)

In [26]:
# find all numbers not divisible by 7
a[~(a % 7 ==0)] # ~ for bitwise not

array([29, 36, 26, 58, 92, 69, 20, 17, 66, 45, 47, 69, 58, 30, 36,  5, 54,
       72, 20, 30, 27, 39], dtype=int32)

## Broadcasting

<h3>The term boardcasting describes how numpy treats arrays with different shapes during arithmetic operations.</h3>
<h3>The smaller array is "broadcast" across the layer array so that they have compatible shapes.</h3>


In [28]:
# same shape
a= np.arange(6).reshape(2,3)
b= np.arange(6,12).reshape(2,3)
print(a)
print(b)

print(a+b)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 6  8 10]
 [12 14 16]]


In [30]:
# diff shape

a= np.arange(6).reshape(2,3)
b= np.arange(3).reshape(1,3)
print(a)
print(b)

print(a+b)

[[0 1 2]
 [3 4 5]]
[[0 1 2]]
[[0 2 4]
 [3 5 7]]


#### Broadcasting Rules

**1. Make the two arrays have the same number of dimensions.**<br>
- If the numbers of dimensions of the two arrays are different, add new dimensions with size 1 to the head of the array with the smaller dimension.<br>

Broadcasting Rules
1. Make the two arrays have the same number of dimensions.

If the numbers of dimensions of the two arrays are different, add new dimensions with size 1 to the head of the array with the smaller dimension.

2. Make each dimension of the two arrays the same size.

If the sizes of each dimension of the two arrays do not match, dimensions with size 1 are stretched to the size of the other array.
If there is a dimension whose size is not 1 in either of the two arrays, it cannot be broadcasted, and an error is raised.

<img src = "https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png">