## Speed comparision

In [37]:
a = [i for i in range(10000000)]
b = [i for i in range(10000000, 20000000)]

c=[]

import time

start=time.time()
for i in range(len(a)):
    c.append(a[i] + b[i])
print(time.time()-start)

1.112009048461914


In [38]:
import numpy as np # use ctype array not referencial array
a=np.arange(10000000)
b=np.arange(10000000, 20000000)
start=time.time()
c=a+b
print(time.time()-start)

0.08374166488647461


In [39]:
1.25/0.09

13.88888888888889

In [40]:
#memory

a=[i for i in range(10000000)]
import sys 
sys.getsizeof(a)

89095160

In [41]:
a=np.arange(10000000,dtype=np.int8)
sys.getsizeof(a)


10000112

In [42]:
#convenience


## Adavnced Indexing

In [43]:
a=np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [44]:
a[1,2] # indexing

np.int64(6)

In [45]:
a[1:3,1:3] #slicing

array([[ 5,  6],
       [ 9, 10]])

In [46]:
#Fancy Indexing
# a[::2]

a[[0,2,3,5]]


array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [47]:
a=np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [48]:
import numpy as np

a = np.arange(24).reshape(6, 4)
print(a)



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [49]:
a = a[:, [0, 2, 3]]
print(a)

[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]
 [12 14 15]
 [16 18 19]
 [20 22 23]]


In [3]:
# Boolean Indexing
import numpy as np
a=np.random.randint(1,100,24).reshape(6,4)
a

array([[ 8, 36, 86, 46],
       [66, 57,  8, 38],
       [17, 65, 73,  6],
       [90, 21, 38, 73],
       [45, 67, 85, 29],
       [ 8, 25, 25, 23]], dtype=int32)

In [4]:
# find all values greater than 50
a>50

array([[False, False,  True, False],
       [ True,  True, False, False],
       [False,  True,  True, False],
       [ True, False, False,  True],
       [False,  True,  True, False],
       [False, False, False, False]])

In [5]:
a[a>50]

array([86, 66, 57, 65, 73, 90, 73, 67, 85], dtype=int32)