<h1>Cretaing Numpy Arrays</h1>

In [4]:
import numpy as np
a=np.array([1,2,3,4])

# print(type(a))
print(a)

[1 2 3 4]


In [6]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [8]:
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) # tensor 3D array
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [9]:
np.array([1,2,3,4],dtype=float)


array([1., 2., 3., 4.])

In [11]:
np.array([1,2,3,4],dtype=bool)

array([ True,  True,  True,  True])

In [12]:
np.array([1,2,3,4],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [14]:
# np.arange

# np.arange(1,11)
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [18]:
# with reshape

np.arange(1,11).reshape(5,2)
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [19]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
#np.random
np.random.random((3,4))

array([[0.55944667, 0.92987498, 0.70867308, 0.91033056],
       [0.11918255, 0.91129365, 0.73746875, 0.33859946],
       [0.91335501, 0.82912107, 0.78152109, 0.3874016 ]])

In [23]:
# np.linspace
np.linspace(-10,10,10) # create the point of same distance

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [25]:
#np.identity
np.identity(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

<h1>Array Attributes</h1>

In [26]:
np.arange(8).reshape(2,2,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [30]:
a1= np.arange(10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

a1
a2
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [31]:
#ndim
a1.ndim

1

In [33]:
a2.ndim

2

In [34]:
a3.ndim

3

In [35]:
#shape
a1.shape

(10,)

In [36]:
a2.shape

(3, 4)

In [37]:
a3.shape

(2, 2, 2)

In [38]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [39]:
#size
a3.size #return items

8

In [40]:
a2.size

12

In [41]:
#itemsize

a1.itemsize

8

In [42]:
a2.itemsize

8

In [43]:
a3.itemsize

8

In [44]:
#dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


<h1>Changing Datatype</h1>

In [45]:
#astype

a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [47]:
a3.dtype

dtype('int64')

In [48]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

<h1>Array Operations</h1>

In [64]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)

a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [55]:
#scalar operations

#arithmetic
a1**2
a1/2
a1+2
a1-2

array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [58]:
#relational
a2>15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [59]:
a2==15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [63]:
#vector operations
a1**a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

# Array Functions

In [67]:
a1=np.random.random((3,3))
a1=np.round(a1*100)
a1

array([[25., 54., 41.],
       [93., 98., 61.],
       [77., 67., 91.]])

In [69]:
#max/min/sum/prod

np.max(a1)

np.float64(98.0)

In [70]:
np.min(a1)

np.float64(25.0)

In [71]:
np.sum(a1)

np.float64(607.0)

In [72]:
np.prod(a1)

np.float64(1.44465253723791e+16)

In [74]:
#mean/median/std/prod
# 0-> col and 1 -> row
np.max(a1,axis=0)

array([93., 98., 91.])

In [75]:
np.max(a1,axis=1)

array([54., 98., 91.])

In [77]:
np.sum(a1,axis=0)

array([195., 219., 193.])

In [81]:
np.var(a1,axis=0)

array([842.66666667, 340.66666667, 422.22222222])

In [82]:
#trigonmetric function
np.sin(a1)

array([[-0.13235175, -0.55878905, -0.15862267],
       [-0.94828214, -0.57338187, -0.96611777],
       [ 0.99952016, -0.85551998,  0.10598751]])

In [88]:
#dot product
a2 =np.arange(12).reshape(3,4)
a3=np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [89]:
#log and exponents
np.log(a1)

array([[3.21887582, 3.98898405, 3.71357207],
       [4.53259949, 4.58496748, 4.11087386],
       [4.34380542, 4.20469262, 4.51085951]])

In [90]:
np.exp(a1)

array([[7.20048993e+10, 2.83075330e+23, 6.39843494e+17],
       [2.45124554e+40, 3.63797095e+42, 3.10429794e+26],
       [2.75851345e+33, 1.25236317e+29, 3.31740010e+39]])

In [94]:
#round/floor/ceil

np.round(np.random.random((2,3))*100)


array([[50.,  5., 89.],
       [11., 65., 39.]])

In [95]:
np.floor(np.random.random((2,3))*100)

array([[42., 50., 44.],
       [ 2., 87., 36.]])

In [96]:
np.ceil(np.random.random((2,3))*100)

array([[75., 73., 87.],
       [35., 14., 91.]])

# Indexing and Slicing

In [97]:
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)


In [98]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
a1[-1]

np.int64(9)

In [100]:
a1[0]

np.int64(0)

In [101]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [102]:
a2[1,2]

np.int64(6)

In [103]:
a2[2,3]

np.int64(11)

In [104]:
a2[1,0]

np.int64(4)

In [105]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [106]:
a3[1,0,1]

np.int64(5)

In [107]:
a3[0,1,0]

np.int64(2)

In [108]:
a3[0,0,0]

np.int64(0)

In [109]:
a4=np.arange(16).reshape(2,2,2,2)
a4

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [110]:
a4[0,0,0,0]

np.int64(0)

In [111]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [113]:
a1[2:5:2]

array([2, 4])

In [114]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [136]:
a2[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [130]:
a2[:1]

array([[0, 1, 2, 3]])

In [131]:
a2[1,::3]

array([4, 7])

In [118]:
a2[:,2]

array([ 2,  6, 10])

In [119]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [120]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [124]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [140]:
a3=np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [150]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [146]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [145]:
a3[1,:,1]

array([10, 13, 16])

In [144]:
a3[0,1,:]

array([3, 4, 5])

In [141]:
a3[1,:,:]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [143]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

## Iterating

In [155]:
a1

for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [156]:
a2

for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [157]:
a3
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [159]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# Reshaping

In [160]:
# Transpose

a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [163]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [164]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [167]:
# Ravel
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [168]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# Stacking

In [169]:

#horizontal stacking
a5=np.arange(12).reshape(3,4)
a6=np.arange(12,24).reshape(3,4)
a5

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [170]:
a6

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [172]:
np.hstack((a5,a6,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11]])

In [173]:
np.vstack((a5,a6,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# Spliting

In [174]:
a5

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [178]:
np.hsplit(a5,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [179]:
np.vsplit(a6,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]